-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email_verified_at timestamp(0) without time zone,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'active'::character varying,
    phone_number character varying(20) COLLATE pg_catalog."default",
    last_login timestamp(0) without time zone,
    remember_token character varying(100) COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    google_id character varying(191) COLLATE pg_catalog."default",
    avatar_url character varying(191) COLLATE pg_catalog."default",
    auth_provider character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'email'::character varying,
    google_verified_at timestamp(0) without time zone,
    institution_id uuid,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_unique UNIQUE (email),
    CONSTRAINT users_google_id_unique UNIQUE (google_id)
);

CREATE TABLE IF NOT EXISTS public.institutions
(
    id uuid NOT NULL,
    name character varying(191) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    phone_number character varying(20) COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    company_type character varying(100) COLLATE pg_catalog."default",
    company_email character varying(150) COLLATE pg_catalog."default",
    CONSTRAINT institutions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.logbook_template
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_by uuid,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    institution_id uuid,
    CONSTRAINT logbook_template_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.logbook_exports
(
    id uuid NOT NULL,
    template_id uuid NOT NULL,
    exported_by uuid NOT NULL,
    file_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    file_type character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'docx'::character varying,
    file_path character varying(500) COLLATE pg_catalog."default" NOT NULL,
    file_url character varying(500) COLLATE pg_catalog."default" NOT NULL,
    file_size bigint NOT NULL DEFAULT '0'::bigint,
    total_entries integer NOT NULL DEFAULT 0,
    total_fields integer NOT NULL DEFAULT 0,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'completed'::character varying,
    error_message text COLLATE pg_catalog."default",
    ip_address character varying(45) COLLATE pg_catalog."default",
    user_agent text COLLATE pg_catalog."default",
    expires_at timestamp(0) without time zone,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT logbook_exports_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.logbook_fields
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    data_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    template_id uuid NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT logbook_fields_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.logbook_datas
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    template_id uuid NOT NULL,
    writer_id uuid NOT NULL,
    data json NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT logbook_datas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.logbook_data_verifications
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    data_id uuid NOT NULL,
    verifier_id uuid NOT NULL,
    is_verified boolean NOT NULL DEFAULT true,
    verified_at timestamp(0) without time zone,
    verification_notes text COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT logbook_data_verifications_pkey PRIMARY KEY (id),
    CONSTRAINT unique_data_verifier UNIQUE (data_id, verifier_id)
);

CREATE TABLE IF NOT EXISTS public.user_logbook_access
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid NOT NULL,
    logbook_template_id uuid NOT NULL,
    logbook_role_id integer NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT user_logbook_access_pkey PRIMARY KEY (id),
    CONSTRAINT user_template_unique UNIQUE (user_id, logbook_template_id)
);

CREATE TABLE IF NOT EXISTS public.logbook_roles
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT logbook_roles_pkey PRIMARY KEY (id),
    CONSTRAINT logbook_roles_name_unique UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.logbook_role_permissions
(
    id serial NOT NULL,
    logbook_role_id integer NOT NULL,
    logbook_permission_id integer NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT logbook_role_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT logbook_role_permission_unique UNIQUE (logbook_role_id, logbook_permission_id)
);

CREATE TABLE IF NOT EXISTS public.logbook_permissions
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT logbook_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT logbook_permissions_name_unique UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.available_templates
(
    id uuid NOT NULL,
    name character varying(191) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    institution_id uuid,
    created_by uuid,
    required_columns jsonb NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT available_templates_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.available_templates.name
    IS 'Nama template';

COMMENT ON COLUMN public.available_templates.description
    IS 'Deskripsi template';

COMMENT ON COLUMN public.available_templates.institution_id
    IS 'Institusi yang membuat template ini';

COMMENT ON COLUMN public.available_templates.created_by
    IS 'User yang membuat template';

COMMENT ON COLUMN public.available_templates.required_columns
    IS 'Array of columns dengan format: [{"name": "Nama Kegiatan", "data_type": "text"}, ...]';

COMMENT ON COLUMN public.available_templates.is_active
    IS 'Status aktif template';

CREATE TABLE IF NOT EXISTS public.feedbacks
(
    id uuid NOT NULL,
    status character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'new'::character varying,
    priority character varying(255) COLLATE pg_catalog."default",
    subject character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    category character varying(255) COLLATE pg_catalog."default",
    questionnaire_responses jsonb,
    rating smallint,
    user_id uuid,
    assigned_to uuid,
    resolved_by uuid,
    response text COLLATE pg_catalog."default",
    response_at timestamp(0) without time zone,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    resolved_at timestamp(0) without time zone,
    closed_at timestamp(0) without time zone,
    CONSTRAINT feedbacks_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.feedbacks.questionnaire_responses
    IS 'Jawaban kuesioner tambahan dalam format JSON';

COMMENT ON COLUMN public.feedbacks.rating
    IS 'Rating 1-5';

CREATE TABLE IF NOT EXISTS public.audit_logs
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid,
    action character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    ip_address character varying(45) COLLATE pg_catalog."default",
    user_agent character varying(255) COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_institution_id_foreign FOREIGN KEY (institution_id)
    REFERENCES public.institutions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.logbook_template
    ADD CONSTRAINT logbook_template_created_by_foreign FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS logbook_template_created_by_index
    ON public.logbook_template(created_by);


ALTER TABLE IF EXISTS public.logbook_template
    ADD CONSTRAINT logbook_template_institution_id_foreign FOREIGN KEY (institution_id)
    REFERENCES public.institutions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.logbook_exports
    ADD CONSTRAINT logbook_exports_exported_by_foreign FOREIGN KEY (exported_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS logbook_exports_exported_by_index
    ON public.logbook_exports(exported_by);


ALTER TABLE IF EXISTS public.logbook_exports
    ADD CONSTRAINT logbook_exports_template_id_foreign FOREIGN KEY (template_id)
    REFERENCES public.logbook_template (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS logbook_exports_template_id_index
    ON public.logbook_exports(template_id);


ALTER TABLE IF EXISTS public.logbook_fields
    ADD CONSTRAINT logbook_fields_template_id_foreign FOREIGN KEY (template_id)
    REFERENCES public.logbook_template (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS logbook_fields_template_id_index
    ON public.logbook_fields(template_id);


ALTER TABLE IF EXISTS public.logbook_datas
    ADD CONSTRAINT logbook_datas_template_id_foreign FOREIGN KEY (template_id)
    REFERENCES public.logbook_template (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS logbook_datas_template_id_index
    ON public.logbook_datas(template_id);


ALTER TABLE IF EXISTS public.logbook_datas
    ADD CONSTRAINT logbook_datas_writer_id_foreign FOREIGN KEY (writer_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS logbook_datas_writer_id_index
    ON public.logbook_datas(writer_id);


ALTER TABLE IF EXISTS public.logbook_data_verifications
    ADD CONSTRAINT logbook_data_verifications_data_id_foreign FOREIGN KEY (data_id)
    REFERENCES public.logbook_datas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS logbook_data_verifications_data_id_index
    ON public.logbook_data_verifications(data_id);


ALTER TABLE IF EXISTS public.logbook_data_verifications
    ADD CONSTRAINT logbook_data_verifications_verifier_id_foreign FOREIGN KEY (verifier_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS logbook_data_verifications_verifier_id_index
    ON public.logbook_data_verifications(verifier_id);


ALTER TABLE IF EXISTS public.user_logbook_access
    ADD CONSTRAINT user_logbook_access_logbook_role_id_foreign FOREIGN KEY (logbook_role_id)
    REFERENCES public.logbook_roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_logbook_access
    ADD CONSTRAINT user_logbook_access_logbook_template_id_foreign FOREIGN KEY (logbook_template_id)
    REFERENCES public.logbook_template (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_logbook_access
    ADD CONSTRAINT user_logbook_access_user_id_foreign FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.logbook_role_permissions
    ADD CONSTRAINT logbook_role_permissions_logbook_permission_id_foreign FOREIGN KEY (logbook_permission_id)
    REFERENCES public.logbook_permissions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.logbook_role_permissions
    ADD CONSTRAINT logbook_role_permissions_logbook_role_id_foreign FOREIGN KEY (logbook_role_id)
    REFERENCES public.logbook_roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.available_templates
    ADD CONSTRAINT available_templates_created_by_foreign FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS available_templates_created_by_index
    ON public.available_templates(created_by);


ALTER TABLE IF EXISTS public.available_templates
    ADD CONSTRAINT available_templates_institution_id_foreign FOREIGN KEY (institution_id)
    REFERENCES public.institutions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS available_templates_institution_id_index
    ON public.available_templates(institution_id);


ALTER TABLE IF EXISTS public.feedbacks
    ADD CONSTRAINT feedbacks_assigned_to_foreign FOREIGN KEY (assigned_to)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS feedbacks_assigned_to_index
    ON public.feedbacks(assigned_to);


ALTER TABLE IF EXISTS public.feedbacks
    ADD CONSTRAINT feedbacks_resolved_by_foreign FOREIGN KEY (resolved_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.feedbacks
    ADD CONSTRAINT feedbacks_user_id_foreign FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS feedbacks_user_id_index
    ON public.feedbacks(user_id);


ALTER TABLE IF EXISTS public.audit_logs
    ADD CONSTRAINT audit_logs_user_id_foreign FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS audit_logs_user_id_index
    ON public.audit_logs(user_id);

END;